### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by philippjfr** [conda-forge/jupyter_bokeh-feedstock#3]
Hi @bollwyvl,

Would you mind adding me as a recipe maintainer? Ping @mattpap and @bryevdv in case they want to be added too.

**Comment by bollwyvl** [comment]
You bet! I :heart: having primary maintainers on the teams! I'll add you on #4 when i get around to reviewing the upstream changes and getting it up and running.

Or, perhaps better: make a new PR that supercedes #4, fixes the 3.0 issues, and adds yourself and I will _happily_ merge it!

**Comment by philippjfr** [comment]
Thanks, as far as I can tell the changes in #4 look good.

**Comment by bollwyvl** [comment]
Looks like @philippjfr is up, feel free to have additional maintainers PR themselves! It's easier than playing telephone...

**Comment by philippjfr** [comment]
Thanks @bollwyvl, appreciate it.
